"""Typed, read-only tool capabilities for the OpsMind Agent runtime."""

from opsmind.tools.contracts import (
    IncidentQueryRequest,
    IncidentQueryResponse,
    PermissionQueryRequest,
    PermissionQueryResponse,
    ToolExecutionSummary,
    ToolMode,
    ToolRequest,
    ToolResponse,
    ToolResultStatus,
    WorkOrderQueryRequest,
    WorkOrderQueryResponse,
)
from opsmind.tools.registry import (
    RegisteredTool,
    ToolArgumentsError,
    ToolCall,
    ToolExecutionError,
    ToolInvocationResult,
    ToolPolicyError,
    ToolRegistry,
    ToolRuntimeError,
    ToolSpec,
    UnknownToolError,
)
from opsmind.tools.synthetic import (
    INCIDENT_QUERY_NAME,
    PERMISSION_QUERY_NAME,
    WORK_ORDER_QUERY_NAME,
    SyntheticToolAdapters,
    build_default_tool_registry,
    incident_query,
    permission_query,
    work_order_query,
)

__all__ = [
    "INCIDENT_QUERY_NAME",
    "IncidentQueryRequest",
    "IncidentQueryResponse",
    "PERMISSION_QUERY_NAME",
    "PermissionQueryRequest",
    "PermissionQueryResponse",
    "RegisteredTool",
    "SyntheticToolAdapters",
    "ToolArgumentsError",
    "ToolCall",
    "ToolExecutionError",
    "ToolExecutionSummary",
    "ToolInvocationResult",
    "ToolMode",
    "ToolPolicyError",
    "ToolRegistry",
    "ToolRequest",
    "ToolResponse",
    "ToolResultStatus",
    "ToolRuntimeError",
    "ToolSpec",
    "UnknownToolError",
    "WORK_ORDER_QUERY_NAME",
    "WorkOrderQueryRequest",
    "WorkOrderQueryResponse",
    "build_default_tool_registry",
    "incident_query",
    "permission_query",
    "work_order_query",
]
